name: Test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    
      - name: Read Pull Request Options
        if:  ${{ github.event.pull_request != null }}
        run: |
          echo "BUILD_OPTIONS=$(jq -n -c \
            --arg executeIT  ${{ contains(github.event.pull_request.body, '!executeIT') }} \
            --arg zip  ${{ contains(github.event.pull_request.body, '!zip') }} \
            '{"executeIT" : (if $executeIT then "-Pit" else "" end), "zip" : (if $zip then "-Pall-in-one" else "" end) }')" >> $GITHUB_ENV
                
      - name: Create file
        run: |
          echo "$BUILD_OPTIONS" > hello.txt
          echo "$BUILD_OPTIONS" > hello2.txt
          
      - name: Upload Hello
        uses: actions/upload-artifact@v4
        with:
          name: hello world
          path: hello.txt
          retention-days: 1
          
      - name: Upload Hello 2
        uses: actions/upload-artifact@v4
        with:
          name: hello2
          path: hello2.txt
          retention-days: 1
        
        