name: Test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    
      - name: Read Pull Request Options
        if:  ${{ github.event.pull_request != null }}
        run: |
          echo "BUILD_OPTIONS=$(jq -n -c \
            --arg executeIT  ${{ contains(github.event.pull_request.body, '!executeIT') ? '-Pit' : '' }} \
            '{"executeIT" : $executeIT }')" >> $GITHUB_ENV
                
                
      - name: Create file
        run: |
          echo "hello" > hello.txt
          echo "$BUILD_OPTIONS" > hello2.txt
          
      - name: Upload Hello
        uses: actions/upload-artifact@v4
        with:
          name: hello world
          path: hello.txt
          retention-days: 1
          
      - name: Upload Hello 2
        uses: actions/upload-artifact@v4
        with:
          name: hello2
          path: hello2.txt
          retention-days: 1
            
  clean-artifacts:
    needs: build
    permissions:
      actions: write 
    uses: ./.github/workflows/_reusable_delete-workflow-artifacts.yml
    with:
      excludes: |
        hello world
        
        