name: Create Merge Request Upstream

on:
  workflow_dispatch: 
  push:
    branches: 
      - '1.0.x'

jobs:
  create-merge-pr:
    uses: bonitasoft/github-workflows/.github/workflows/_reusable_create_merge_pr.yml@main
    with:
      labels: automerge,bug
    secrets: 
      BONITA_CI_PAT: ${{ secrets.BONITA_CI_PAT }}