name: Create Merge Request Upstream

on:
  workflow_dispatch: 
  push:
    branches: 
      - '1.0.x'

jobs:
  create-pr:
    runs-on: ubuntu-22.04
    steps:
      - name: Determine upstream branch
        id: upstream-branch
        run: echo "ref=${{ fromJson(vars.SUPPORTED_BRANCHES).upstream-branch[github.ref_name] }}" >> $GITHUB_OUTPUT
      - id: create-pr
        run: |
          gh pr create \ 
          --base ${{ steps.upstream-branch.outputs.ref }}
          --title "[merge] ${{ github.ref_name}} into ${{ steps.upstream-branch.outputs.ref }}"
          --body "Pull request opened automatically. Use Merge Pull Request action (DO NOT SQUASH)"
          --label automerge
      # - uses: peter-evans/create-pull-request@v6
      #   id: create-pr
      #   with:
      #     branch:  origin/${{ github.ref_name }}
      #     base: origin/${{ steps.upstream-branch.outputs.ref }}
      #     title: "[merge] ${{ github.ref_name}} into ${{ steps.upstream-branch.outputs.ref }}"
      #     labels: |
      #       automerge
      #     body: |
      #       This pull request has been automatically opened.
      #       It's purpose is to propagate fixes into upstream branches.