name: Create Merge Request Upstream

on:
  workflow_dispatch: 
  push:
    branches: 
      - '1.0.x'

jobs:
  create-merge-pr:
    uses: bonitasoft/github-workflows/.github/workflows/_reusable_create_merge_pr.yml@main
    secrets: inherit