name: Tag created
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.0'
      - '[0-9]+.[0-9]+.0.alpha-[0-9]+'
      - '[0-9]+.[0-9]+.0.beta-[0-9]+'
      - '[0-9]+.[0-9]+.0.rc-[0-9]+'
      - '[0-9]+.[0-9]+.0.W[0-9]+'
    paths: 
      - 'subpath/**'

jobs:
  test-tag-regex:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo 'github.ref=${{ github.ref}}'
          echo 'github.ref_name=${{ github.ref_name}}'
