name: Release

on:
  workflow_dispatch: 

jobs:
  maven-release:
    runs-on: ubuntu-22.04
    outputs:
      security-version: ${{ steps.release-properties.outputs['project.rel.org.bonitasoft.security:licensing'] }}
      manager-version: ${{  steps.release-properties.outputs['project.rel.org.bonitasoft.security:manager-parent'] }}
    steps:
      - uses: actions/checkout@v4
       
      - uses: BrycensRanch/read-properties-action@v1
        id: release-properties
        with:
          file: release.properties
          all: true


  read-output:
    needs: maven-release
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "security version: ${{ needs.maven-release.outputs.security-version}}"
          echo "manager version: ${{ needs.maven-release.outputs.manager-version}}"