name: Release

on:
  workflow_dispatch: 

jobs:
  maven-release:
    runs-on: ubuntu-22.04
    outputs:
      security-version: ${{ steps.release-properties.outputs.project-rel-org-bonitasoft-security-licensing }}
      manager-version: ${{  steps.release-properties.outputs.project-rel-org-bonitasoft-security-manager-parent }}
    steps:
      - uses: actions/checkout@v4
          
      - name: Read release.properties
        id: release-properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: release.properties
          properties: >
            project.rel.org.bonitasoft.security\:licensing 
            project.rel.org.bonitasoft.security\:manager-parent


  read-output:
    needs: maven-release
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "security version: ${{ needs.maven-release.outputs.security-version}}"
          echo "manager version: ${{ needs.maven-release.outputs.manager-version}}"